-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SpriteKit Test/SpriteKitTest/CLDVViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:51:34 +0000



-- Objective C interface: @interface CLDVViewController
local CLDVViewController = objc.classInterface ("CLDVViewController") --[[ @inherits UIViewController]]
