-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SpriteKit Test/SpriteKitTest/CLDVViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:21:07 +0000



-- Objective C interface: @interface CLDVViewController
local CLDVViewController = objc.classInterface ("CLDVViewController") --[[ @inherits UIViewController]]
